### ISSUE TITLE
'catalog.json' metadata file must be specified for a valid catalog

### ISSUE THREAD

**Issue by LGinC** [MT-Photos/charts#1]
<img width="1268" alt="image" src="https://github.com/MT-Photos/charts/assets/15363011/e8775931-2cdf-44fd-9b5e-6071c6557d0c">

TrueNAS-SCALE-23.10-RC.1

添加应用目录失败

**Comment by LGinC** [comment]
手动部署则一直在提示初始化数据库
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mt-photos-deployment
  namespace: application
  labels:
    app: mt-photos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mt-photos
  template:
    metadata:
      labels:
        app: mt-photos
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      containers:
      - name: mt-photos
        image: mtphotos/mt-photos
        ports:
        - containerPort: 8063
        resources:
          requests:
            cpu: 200m
            memory: 50M
          limits:
            cpu: 2000m
            memory: 2Gi
        env:
        - name: TZ
          value: Asia/Shanghai
        - name: POSTGRES_HOST
          value: pgvector
        - name: POSTGRES_PORT
          value: '5432'
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: mypassword
        - name: POSTGRES_DATABASE
          value: mtphotos
        volumeMounts:
        - name: config
          mountPath: /config
        - name: upload
          mountPath: /upload
      volumes:
        - name: config
          hostPath:
            path: /mnt/nas/mt-photos/config
        - name: upload
          hostPath:
            path: /mnt/nas/mt-photos/upload
```

<img width="752" alt="image" src="https://github.com/MT-Photos/charts/assets/15363011/386be20a-3262-41b3-97f2-87874289841e">

数据库是可以正常连接的
<img width="664" alt="image" src="https://github.com/MT-Photos/charts/assets/15363011/2210c7d9-3e0a-43f4-b385-ce71b46b6801">
